export const CARD_TYPE_EVALUATION = 'EVALUATION';
export const CARD_TYPE_ACCOUNTABILITY_SUBMITTED = 'ACCOUNTABILITY_SUBMITTED';
export const CARD_TYPE_ACCOUNTABILITY_CREATED = 'ACCOUNTABILITY_CREATED';
export const CARD_TYPE_EXPENSE = 'EXPENSE';
