export const CARD_TYPE_EVALUATION = 'EVALUATION';
export const CARD_TYPE_ACCOUNTABILITY_SUBMITTED = 'ACCOUNTABILITY_SUBMITTED';
export const CARD_TYPE_ACCOUNTABILITY_CREATED = 'ACCOUNTABILITY_CREATED';
export const CARD_TYPE_EXPENSE = 'EXPENSE';
export const EXPENSE_CODE_HOTEL = 'hotel-fee';
export const EXPENSE_CODE_FOOD = 'food';
export const STATUS_PEDING = 'PENDING';
